[package]
name = "rkv"
version = "0.3.2"
authors = ["Richard Newman <rnewman@twinql.com>"]
description = "a simple, humane, typed Rust interface to LMDB"
license = "Apache-2.0"
homepage = "https://github.com/mozilla/rkv"
repository = "https://github.com/mozilla/rkv"
readme = "README.md"
keywords = ["lmdb", "database", "storage"]
categories = ["database"]

[features]
default = []
backtrace = ["failure/backtrace", "failure/std"]

[dependencies]
arrayref = "0.3"
bincode = "1.0"
lazy_static = "1.0"
lmdb = "0.7"
ordered-float = "0.5"
uuid = "0.5"
serde = "1.0"
url = "1.7.0"

# Get rid of failure's dependency on backtrace. Eventually
# backtrace will move into Rust core, but we don't need it here.
[dependencies.failure]
version = "0.1"
default_features = false
features = ["derive"]

[dev-dependencies]
byteorder = "1"
tempfile = "3"
