[package]
name = "rkv"
version = "0.10.0"
authors = ["Richard Newman <rnewman@twinql.com>", "Nan Jiang <najiang@mozilla.com>", "Myk Melez <myk@mykzilla.org>", "Victor Porof <vporof@mozilla.com>"]
edition = "2018"
license = "Apache-2.0"
description = "a simple, humane, typed Rust interface to LMDB"
documentation = "https://docs.rs/rkv"
homepage = "https://github.com/mozilla/rkv"
repository = "https://github.com/mozilla/rkv"
readme = "README.md"
keywords = ["lmdb", "database", "storage"]
categories = ["database"]
exclude = ["/tests/envs/*"]

[badges]
travis-ci = { repository = "mozilla/rkv" }
appveyor = { repository = "mozilla/rkv" }

[features]
default = []
backtrace = ["failure/backtrace", "failure/std"]
with-clang = ["lmdb-rkv/with-clang"]
with-asan = ["lmdb-rkv/with-asan"]
with-fuzzer = ["lmdb-rkv/with-fuzzer"]
with-fuzzer-no-link = ["lmdb-rkv/with-fuzzer-no-link"]

[dependencies]
arrayref = "0.3.5"
bincode = "1.1.4"
bitflags = "1.1.0"
byteorder = "1.3.2"
lazy_static = "1.4.0"
lmdb-rkv = "0.12.1"
ordered-float = "1.0.2"
uuid = "0.7.4"
serde = "1.0.100"
serde_derive = "1.0.100"
url = "2.1.0"

# Get rid of failure's dependency on backtrace. Eventually
# backtrace will move into Rust core, but we don't need it here.
[dependencies.failure]
version = "0.1.5"
default_features = false
features = ["derive"]

[dev-dependencies]
byteorder = "1"
tempfile = "3"
