[package]
name = "rkv"
version = "0.10.2"
authors = ["Richard Newman <rnewman@twinql.com>", "Nan Jiang <najiang@mozilla.com>", "Myk Melez <myk@mykzilla.org>", "Victor Porof <vporof@mozilla.com>"]
edition = "2018"
license = "Apache-2.0"
description = "a simple, humane, typed Rust interface to LMDB"
documentation = "https://docs.rs/rkv"
homepage = "https://github.com/mozilla/rkv"
repository = "https://github.com/mozilla/rkv"
readme = "README.md"
keywords = ["lmdb", "database", "storage"]
categories = ["database"]
exclude = ["/tests/envs/*"]

[features]
default = ["with-safe-mode"]
backtrace = ["failure/backtrace", "failure/std"]
with-safe-mode = ["id-arena", "log", "serde/derive"]
with-asan = ["lmdb-rkv/with-asan"]
with-fuzzer = ["lmdb-rkv/with-fuzzer"]
with-fuzzer-no-link = ["lmdb-rkv/with-fuzzer-no-link"]

[dependencies]
arrayref = "0.3"
bincode = "1.0"
bitflags = "1"
byteorder = "1"
id-arena = { version = "2.2", optional = true }
lazy_static = "1.0"
lmdb-rkv = "0.12.3"
log = { version = "0.4", optional = true }
ordered-float = "1.0"
uuid = "0.7"
serde = "1.0"
serde_derive = "1.0"
url = "2.0"

# Get rid of failure's dependency on backtrace. Eventually
# backtrace will move into Rust core, but we don't need it here.
[dependencies.failure]
version = "0.1"
default_features = false
features = ["derive"]

[dev-dependencies]
byteorder = "1"
tempfile = "3"
